name: Test
on:
  workflow_dispatch:
  pull_request:
    paths: ["action.yml", ".github/workflows/test.yml"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  test-specifying-version:
    name: Test specifying version
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Exercise
        uses: ./
        with:
          tfcmt-version: 4.14.0

      - name: Verify
        run: |
          set -x
          actual="$(tfcmt --version)"
          grep 'tfcmt version 4.14.0' <<<"${actual}"

  test-latest-version:
    name: Test latest version
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Exercise
        uses: ./
        with:
          tfcmt-version: latest

      - name: Verify
        run: |
          set -x
          actual="$(tfcmt --version)"
          grep 'tfcmt version 4.' <<<"${actual}"

  test-omit-version:
    name: Test omit version
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Exercise
        uses: ./

      - name: Verify tfcmt
        run: |
          set -x
          actual="$(tfcmt --version)"
          grep 'tfcmt version 4.' <<<"${actual}"
